apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-minesweeper
  labels:
    app: vue-minesweeper
spec:
  replicas: 2 # 启动两个 Pod 副本6
  selector:
    matchLabels:
      app: vue-minesweeper
  template:
    metadata:
      labels:
        app: vue-minesweeper
    spec:
      containers:
      - name: web
        image: frontend:latest   # <--- 请注意！这就是我们留给 CI 替换的靶子！
        ports:
        - containerPort: 80