apiVersion: v1
kind: Service
metadata:
  name: vue-minesweeper-svc
spec:
  type: NodePort # 方便你部署完直接通过节点 IP 访问
  selector:
    app: vue-minesweeper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80